# Generated by Django 3.2.23 on 2024-01-31 00:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('profileName', models.CharField(max_length=255, verbose_name='Nome do perfil')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('postID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkPost', models.CharField(max_length=255, verbose_name='Link pessoal')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da publicação')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.FileField(upload_to='imagens', verbose_name='Imagem do post')),
                ('likes', models.IntegerField(verbose_name='Likes na publicação')),
                ('reads', models.IntegerField(verbose_name='Leituras na publicação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
            options={
                'verbose_name': 'Discussão',
                'verbose_name_plural': 'Discussões',
            },
        ),
    ]
