# Generated by Django 3.2.23 on 2024-02-03 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('logID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('subTitle', models.CharField(max_length=255, verbose_name='Sub-título')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data do log')),
                ('image', models.FileField(upload_to='imagensLog', verbose_name='Imagem do log')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
