# Generated by Django 3.2.23 on 2024-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'Mudança', 'verbose_name_plural': 'Mudanças'},
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='fotosUsuários', verbose_name='Foto de usuário'),
        ),
    ]
