# Generated by Django 3.2.23 on 2024-02-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20240211_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussions',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes na publicação'),
        ),
        migrations.AlterField(
            model_name='discussions',
            name='reads',
            field=models.IntegerField(default=0, verbose_name='Leituras na publicação'),
        ),
    ]
