# Generated by Django 3.2.23 on 2024-02-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20240211_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussions',
            name='image',
            field=models.FileField(upload_to='img', verbose_name='Imagem do post'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='image',
            field=models.FileField(upload_to='img', verbose_name='Imagem'),
        ),
    ]
