# Generated by Django 3.2.23 on 2024-02-14 01:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20240211_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Comentário')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('commented_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.discussions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.user')),
            ],
        ),
    ]
