# Generated by Django 3.2.23 on 2024-02-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes no comentário'),
        ),
    ]
