# Generated by Django 3.2.23 on 2024-02-16 20:59

import Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_discussions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='image',
            field=models.ImageField(upload_to=Api.models.upload_image_logs, verbose_name='Imagem'),
        ),
    ]
