# Generated by Django 3.2.23 on 2024-02-16 21:06

import Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_logs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Api.models.upload_image_logs, verbose_name='Imagem'),
        ),
    ]
