# Generated by Django 3.2.23 on 2024-02-23 14:05

import Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_alter_logs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Api.models.upload_image_discussion, verbose_name='Imagem do post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Api.models.upload_image_user, verbose_name='Foto de usuário'),
        ),
    ]
