# Generated by Django 3.2.23 on 2024-06-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_auto_20240223_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profileName',
            new_name='username',
        ),
    ]
